# Generated by Django 4.2.1 on 2023-12-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0004_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomPETaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('class_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildforge_api.classmember')),
                ('class_room_pe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildforge_api.classroompe')),
            ],
        ),
    ]
