# Generated by Django 4.2.1 on 2023-12-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0005_classroompetaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroompetaker',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
