# Generated by Django 4.2.1 on 2024-01-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0006_classroompetaker_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroompetaker',
            name='data',
        ),
        migrations.AddField(
            model_name='peereval',
            name='sheet_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
